

export const LOGOUT_COMPANY = 'LOGOUT_COMPANY'

export const SET_COMPANY_BEGIN = 'SET_COMPANY_BEGIN'
export const SET_COMPANY_SUCCESS = 'SET_COMPANY_SUCCESS'
export const SET_COMPANY_ERROR = 'SET_COMPANY_ERROR'

export const LOGIN_COMPANY_BEGIN = 'LOGIN_COMPANY_BEGIN'
export const LOGIN_COMPANY_SUCCESS = 'LOGIN_COMPANY_SUCCESS'
export const LOGIN_COMPANY_ERROR = 'LOGIN_COMPANY_ERROR'

export const LOGIN_EMPLOYEE_BEGIN = 'LOGIN_EMPLOYEE_BEGIN'
export const LOGIN_EMPLOYEE_SUCCESS = 'LOGIN_EMPLOYEE_SUCCESS'
export const LOGIN_EMPLOYEE_ERROR = 'LOGIN_EMPLOYEE_ERROR'


export const GET_ALL_EMPLOYEES_BEGIN = 'GET_ALL_EMPLOYEES_BEGIN'
export const GET_ALL_EMPLOYEES_SUCCESS = 'GET_ALL_EMPLOYEES_SUCCESS'
export const GET_ALL_EMPLOYEES_ERROR = 'GET_ALL_EMPLOYEES_ERROR'

export const GET_ALL_TASKS_BEGIN = 'GET_ALL_TASKS_BEGIN'
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS'
export const GET_ALL_TASKS_ERROR = 'GET_ALL_TASKS_ERROR'  

export const GET_TASK_BY_SEARCH_BEGIN = 'GET_TASK_BY_SEARCH_BEGIN'
export const GET_TASK_BY_SEARCH_SUCCESS = 'GET_TASK_BY_SEARCH_SUCCESS'
export const GET_TASK_BY_SEARCH_ERROR = 'GET_TASK_BY_SEARCH_ERROR'

