

export const LOGOUT_COMPANY = 'LOGOUT_COMPANY'

export const SET_COMPANY_BEGIN = 'SET_COMPANY_BEGIN'
export const SET_COMPANY_SUCCESS = 'SET_COMPANY_SUCCESS'
export const SET_COMPANY_ERROR = 'SET_COMPANY_ERROR'

export const LOGIN_COMPANY_BEGIN = 'LOGIN_COMPANY_BEGIN'
export const LOGIN_COMPANY_SUCCESS = 'LOGIN_COMPANY_SUCCESS'
export const LOGIN_COMPANY_ERROR = 'LOGIN_COMPANY_ERROR'


export const GET_ALL_EMPLOYEES_BEGIN = 'GET_ALL_EMPLOYEES_BEGIN'
export const GET_ALL_EMPLOYEES_SUCCESS = 'GET_ALL_EMPLOYEES_SUCCESS'
export const GET_ALL_EMPLOYEES_ERROR = 'GET_ALL_EMPLOYEES_ERROR'

