

export const LOGOUT_USER = 'LOGOUT_USER'

export const SET_COMPANY_BEGIN = 'SET_COMPANY_BEGIN'
export const SET_COMPANY_SUCCESS = 'SET_COMPANY_SUCCESS'
export const SET_COMPANY_ERROR = 'SET_COMPANY_ERROR'

export const LOGIN_COMPANY_BEGIN = 'LOGIN_COMPANY_BEGIN'
export const LOGIN_COMPANY_SUCCESS = 'LOGIN_COMPANY_SUCCESS'
export const LOGIN_COMPANY_ERROR = 'LOGIN_COMPANY_ERROR'

